apiVersion: v1
data:
  batman-client.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: batman-client
      namespace: kube-system
      labels:
        app: batman-client
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      selector:
        matchLabels:
          app: batman-client
      template:
        metadata:
          name: batman-client
          labels:
            app: batman-client
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: batman
                    operator: NotIn
                    values:
                    - gateway
          restartPolicy: Always
          priorityClassName: "system-node-critical"
          tolerations:
            - key: "node.cloudprovider.kubernetes.io/uninitialized"
              value: "true"
              effect: "NoSchedule"          
            - key: "CriticalAddonsOnly"
              operator: "Exists"
            - key: "node.kubernetes.io/not-ready"
              effect: "NoExecute"
          containers:
            - name: batman-client
              image: rinawolfeak/batmanclient
              imagePullPolicy: Always 
              securityContext:
                runAsNonRoot: false
                readOnlyRootFilesystem: false
                privileged: true
                allowPrivilegeEscalation: true
              env:
                - name: MESH_NAME
                  value: mesh-iot
                - name: BAT_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP 
              volumeMounts:
                - mountPath: /etc
                  name: etc
          dnsPolicy: ClusterFirst
          hostNetwork: true  
          hostPID: true
          hostIPC: true            
          volumes:
            - name: etc
              hostPath:
                path: /etc
kind: ConfigMap
metadata:
  name: batman-client
  namespace: default